# set the base image
FROM microsoft/aspnercore-build:latest
WORKDIR /app

# copy the project file to working director
# restore the application
COPY project.json .
RUN dotnet restore

# copy everything else abd publish/build
COPY . .
RUN dotnet publish -c Release -o out

# expose port 5000
Expose 5000

# run the asp.net core app
ENTRYPOINT ["dotnet", "out/app/sso.dll"]

